// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NMS.Saga.Sample.Kachar.DataLayer;

namespace NMS.Saga.Sample.Kachar.Migrations
{
    [DbContext(typeof(KacharDbContext))]
    [Migration("20200417150949_DisableAutoGenId")]
    partial class DisableAutoGenId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NMS.Saga.Sample.Contracts.Models.Coding", b =>
                {
                    b.Property<int>("IdCoding");

                    b.Property<string>("Title");

                    b.HasKey("IdCoding");

                    b.ToTable("Coding");
                });
#pragma warning restore 612, 618
        }
    }
}
