version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    container_name: rabbitmq-instance
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
